---
title: "Class17"
author: "Andres Rivero"
date: "11/24/2021"
output:
  pdf_document:
    latex_engine: xelatex
    
---


```{r}
vax <- read.csv("covid19vaccinesbyzipcode_test.csv")
head(vax)
```
```{r}
nrow(vax)
```

```{r}
skimr::skim(vax)
```

```{r}
library(lubridate)
```

```{r}
today()
```
```{r}
vax$as_of_date[1]
```

```{r}
vax$as_of_date <- ymd(vax$as_of_date)
```

```{r}
today() - vax$as_of_date[1]
```

```{r}
today() - vax$as_of_date[nrow(vax)]
```

```{r}
vax$as_of_date[nrow(vax)] - vax$as_of_date[1]
```
```{r}
length(unique((vax$zip_code_tabulation_area)))
```

```{r}
library(zipcodeR)
```
```{r}
geocode_zip('92037')
```

```{r}
zip_distance('92037','92109')
```

```{r}
reverse_zipcode(c('92037', "92109") )
```

```{r}
library(dplyr)
```
```{r}
inds <- vax$county == "San Diego"
nrow(vax[inds,])
```

```{r}
sd <- filter(vax, county == "San Diego")
nrow(sd)
```
```{r}
sd.20 <- filter(vax, county == "San Diego" &
                age5_plus_population > 20000)
nrow(sd.20)
```
```{r}
sd.now <- filter(sd, as_of_date == "2021-11-23")
summary(sd.now$percent_of_population_fully_vaccinated)
```

```{r}
hist(sd.now$percent_of_population_fully_vaccinated)
```
```{r}
head(sd.now)
lj <- filter(sd.now, zip_code_tabulation_area == "92037")
```

```{r}
lj$age5_plus_population
```
```{r}
lj$percent_of_population_fully_vaccinated
```
```{r}
lj2 <- filter(sd.now, zip_code_tabulation_area == "92122")
lj2$age5_plus_population
lj2$percent_of_population_fully_vaccinated
```
```{r}
library(ggplot2)
```

```{r}
lj3 <- filter(vax, zip_code_tabulation_area == "92037")

ggplot(lj3) +
  aes(x=as_of_date,
      y=percent_of_population_fully_vaccinated) +
  geom_point() +
  geom_line(group=1) + ylim(c(0,1)) +
  labs(x= "Date", y="Percent Vaccinated")
```

```{r}
 sd.36<- filter(vax, county== "San Diego", age5_plus_population>36144 )
head(sd.36)
length(unique(sd.36$zip_code_tabulation_area))

```

```{r}
ggplot(sd.36) +
  aes(x=as_of_date,
      y=percent_of_population_fully_vaccinated, group=zip_code_tabulation_area) +
  geom_line() + ylim(c(0,1)) +
  labs(x= "Date", y="Percent Vaccinated")
```
```{r}
ca<- filter(vax, age5_plus_population>36144 )
length(unique(ca$zip_code_tabulation_area))
```


```{r}
ggplot(ca) +
  aes(x=as_of_date,
      y=percent_of_population_fully_vaccinated, group=zip_code_tabulation_area) +
  geom_line(alpha=0.2) + ylim(c(0,1)) +
  labs(x= "Date", y="Percent Vaccinated")
```
```{r}
ca.now <- filter(ca, as_of_date== "2021-11-23")
summary(ca.now$percent_of_population_fully_vaccinated)
```
```{r}
ggplot(ca) +
  aes(x=as_of_date,
      y=percent_of_population_fully_vaccinated, group=zip_code_tabulation_area) +
  geom_line(alpha=0.2) + ylim(c(0,1)) +
  labs(x= "Date", y="Percent Vaccinated") +
  geom_hline(yintercept = mean(ca.now$percent_of_population_fully_vaccinated), linetype= 2, color="red")

  
```

